[package]
name = "niche_boy_advance"
version = "0.1.0"
authors = ["Dylan Jenkins <dylanljenkins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#hex = "0.4.3"
minifb = "0.19.3"